# Generated by Django 3.2.3 on 2021-06-25 08:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Patient Name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Patient Age')),
                ('nid', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{10}|\\d{13}|\\d{17})$', message='Numeric 10/13/17 digits (ex: 1234567890)')], verbose_name='National ID')),
                ('post_code', models.PositiveIntegerField(help_text='Numeric 4 digits (ex: 1234)', null=True, validators=[django.core.validators.RegexValidator('^[\\d]{4}$', message='Numeric 4 digits (ex: 1234)')])),
                ('address', models.TextField(help_text='Ex: 2/17, Mirpur-11', null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_district', to='address.district')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_division', to='address.division')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_upazila', to='address.upazila')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
