# Generated by Django 3.2.3 on 2021-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Patient/'),
        ),
    ]
