# Generated by Django 3.2.3 on 2021-06-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0004_doctorappointment_appointment_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='problem',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Problem'),
        ),
    ]
