# Generated by Django 3.2.3 on 2021-07-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_speciality_options'),
        ('patient_ms', '0005_doctorappointment_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_speciality', to='hospital.speciality'),
        ),
    ]
