# Generated by Django 3.2.3 on 2021-07-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('patient_ms', '0006_doctorappointment_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_district', to='address.district'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_division', to='address.division'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_upazila', to='address.upazila'),
        ),
    ]
