# Generated by Django 3.2.3 on 2021-07-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0008_auto_20210704_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='appointment_day',
            field=models.DateField(blank=True, null=True, verbose_name='Appointment Day'),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_close_time',
            field=models.DateField(blank=True, null=True, verbose_name='Appointment Close Time'),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Appointment Time'),
        ),
    ]
