# Generated by Django 3.2.3 on 2021-07-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ms', '0013_doctorprescription_recordfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordfile',
            name='document',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
