# Generated by Django 3.2.3 on 2021-07-12 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient_ms', '0014_alter_recordfile_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
