# Generated by Django 3.2.3 on 2021-06-22 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0013_auto_20210523_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.TextField(help_text='Ex: 2/17, Mirpur-11', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_district', to='address.district'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_division', to='address.division'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='post_code',
            field=models.PositiveIntegerField(help_text='Numeric 4 digits (ex: 1234)', null=True, validators=[django.core.validators.RegexValidator('^[\\d]{4}$', message='Numeric 4 digits (ex: 1234)')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_upazila', to='address.upazila'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nid', models.CharField(max_length=120)),
                ('picture', models.ImageField(upload_to='patient/')),
                ('bio', models.TextField()),
                ('post_code', models.PositiveIntegerField(help_text='Numeric 4 digits (ex: 1234)', null=True, validators=[django.core.validators.RegexValidator('^[\\d]{4}$', message='Numeric 4 digits (ex: 1234)')])),
                ('address', models.TextField(help_text='Ex: 2/17, Mirpur-11', null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_district', to='address.district')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_division', to='address.division')),
                ('upazila', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_upazila', to='address.upazila')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
