# Generated by Django 3.2.3 on 2021-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20210622_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='expertize',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.Expertize'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(null=True, upload_to='doctors/'),
        ),
    ]
