# Generated by Django 3.2.3 on 2021-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_auto_20210623_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='expertize',
            field=models.ManyToManyField(blank=True, to='hospital.Expertize'),
        ),
    ]
