# Generated by Django 3.2.3 on 2021-06-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_alter_doctor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
