# Generated by Django 3.2.3 on 2021-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
