# Generated by Django 3.2.3 on 2021-07-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20210703_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'Doctor Speciality'},
        ),
    ]
