# Generated by Django 3.2.3 on 2021-07-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_speciality_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='present_hospital',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
